apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- podinfo-dep.yaml
- podinfo-hpa.yaml
- podinfo-svc.yaml
- demo.yaml
- mongodb.yaml
- ghost.yaml
- redis.yaml
- redis-auth.yaml